"""Topics, keywords and filler vocabulary. Data only, so the generator reads as generation.

Every topic carries a keyword that a person writing on that topic would use anyway. The keyword
is a second checkable requirement, and it is here because the counting constraint ALONE is
trivially satisfiable: a program that emits the word `item` the requested number of times scores
full marks and has said nothing. The keyword does not fix that, and the README says so, but it
does stop the very cheapest strategy from being invisible in the leaderboard.

The filler vocabulary is chosen for what it does NOT contain: no hyphens, no digits, no
apostrophes and no characters outside ASCII, so a padded answer's word count is the same under
every dialect in `rules.py` and the reference answers cannot accidentally become a test of the
dialects rather than of the counters.
"""

TOPICS = (
    ("the water cycle", "condensation"),
    ("how bread rises", "yeast"),
    ("why the sky looks blue", "scattering"),
    ("the rules of chess", "checkmate"),
    ("how a bicycle stays upright", "steering"),
    ("the life of a honeybee colony", "forage"),
    ("what makes a good sentence", "clarity"),
    ("how paper is recycled", "pulp"),
    ("the history of the printing press", "movable"),
    ("how a refrigerator keeps food cold", "compressor"),
    ("the parts of a violin", "bridge"),
    ("why leaves change colour in autumn", "chlorophyll"),
    ("how a lock and key work", "tumbler"),
    ("the job of a lighthouse keeper", "beacon"),
    ("how coffee is roasted", "roast"),
    ("the difference between weather and climate", "average"),
    ("how a suspension bridge carries load", "cable"),
    ("what happens during a total eclipse", "shadow"),
    ("how sourdough starter is kept alive", "flour"),
    ("the anatomy of a wave", "trough"),
    ("how a sewing machine forms a stitch", "bobbin"),
    ("why ice floats", "density"),
    ("the work of a river delta", "sediment"),
    ("how a piano action works", "hammer"),
    ("the migration of monarch butterflies", "migration"),
    ("how glass is blown", "furnace"),
    ("what a compass actually points at", "magnetic"),
    ("how sound travels through water", "pressure"),
    ("the making of a wooden barrel", "stave"),
    ("how a kite flies", "lift"),
    ("what yeast does to grape juice", "fermentation"),
    ("the design of a Roman aqueduct", "gradient"),
    ("how a camera lens focuses", "aperture"),
    ("why bread goes stale", "starch"),
    ("the layers of the atmosphere", "troposphere"),
    ("how a windmill grinds grain", "millstone"),
    ("what makes a knot hold", "friction"),
    ("the growth of a coral reef", "polyp"),
    ("how ink is made", "pigment"),
    ("the phases of the moon", "waxing"),
    ("how a thermostat decides to switch on", "threshold"),
    ("the parts of a shoe", "sole"),
    ("how salt is harvested from the sea", "evaporation"),
    ("why cast iron pans are seasoned", "polymerised"),
    ("the flight of a boomerang", "gyroscopic"),
    ("how a well is dug", "aquifer"),
    ("the language of bees", "waggle"),
    ("how a candle burns", "wick"),
    ("what a keel does on a sailing boat", "keel"),
    ("the making of cheese", "rennet"),
    ("how a bell is cast", "bronze"),
    ("why rainbows are curved", "refraction"),
    ("the tools of a stonemason", "chisel"),
    ("how a zip fastener works", "slider"),
    ("the smell of rain on dry ground", "petrichor"),
    ("how a seed knows which way is up", "gravitropism"),
    ("the making of a violin bow", "horsehair"),
    ("how tides are caused", "gravitational"),
    ("what a sundial measures", "gnomon"),
    ("the building of a dry stone wall", "coping"),
    ("how a submarine changes depth", "ballast"),
    ("why onions make people cry", "sulphur"),
    ("the work of an archivist", "provenance"),
    ("how a whistle makes its note", "resonance"),
)

FORMS = {
    "prose": (
        "Write a short explanation of {topic}.",
        "Write a paragraph about {topic}.",
        "Write a brief note describing {topic}.",
        "Write a short summary of {topic} for a curious reader.",
        "Explain {topic} to someone who has never thought about it.",
    ),
    "list": (
        "Write a list of facts about {topic}.",
        "Write a list of things worth knowing about {topic}.",
        "List the steps or parts involved in {topic}.",
        "Write a list of observations about {topic}.",
    ),
    "block": (
        "Write a short piece about {topic}.",
        "Write a few blocks of prose about {topic}.",
    ),
}

# Padding vocabulary, grouped by length so a character target can be hit exactly. Nothing here
# carries a hyphen, an apostrophe, a digit or a character outside ASCII.
FILLER = (
    "a", "an", "as", "at", "by", "in", "is", "it", "of", "on", "or", "so", "to", "up", "we",
    "and", "are", "but", "can", "day", "end", "few", "for", "its", "may", "new", "not", "one",
    "our", "out", "own", "see", "the", "two", "use", "way", "who", "why", "yet",
    "also", "back", "been", "both", "case", "come", "each", "even", "form", "from", "give",
    "hand", "have", "here", "hold", "into", "keep", "kind", "less", "like", "long", "made",
    "make", "many", "more", "most", "much", "must", "near", "need", "next", "once", "only",
    "open", "over", "part", "past", "same", "seem", "show", "side", "size", "some", "such",
    "sure", "take", "than", "that", "them", "then", "they", "this", "time", "turn", "used",
    "very", "well", "were", "what", "when", "will", "with", "work", "year",
    "about", "after", "again", "along", "among", "begin", "being", "below", "break", "bring",
    "carry", "cause", "clear", "close", "count", "cover", "early", "every", "field", "first",
    "found", "front", "given", "group", "hands", "human", "known", "large", "learn", "leave",
    "level", "light", "local", "loose", "lower", "makes", "means", "might", "money", "never",
    "often", "order", "other", "place", "point", "power", "quite", "range", "reach", "ready",
    "right", "round", "sense", "shape", "share", "short", "since", "small", "sound", "space",
    "stand", "start", "still", "story", "study", "table", "taken", "these", "thing", "think",
    "third", "those", "three", "under", "until", "using", "value", "watch", "water", "where",
    "which", "while", "whole", "whose", "world", "would", "write", "years",
    "across", "almost", "always", "amount", "answer", "around", "become", "before", "behind",
    "better", "beyond", "camera", "cannot", "centre", "change", "choice", "closed", "coming",
    "common", "detail", "during", "either", "enough", "expect", "figure", "follow", "forget",
    "friend", "future", "ground", "growth", "happen", "hardly", "having", "indeed", "inside",
    "island", "itself", "leaves", "length", "letter", "little", "living", "making", "matter",
    "method", "middle", "moment", "narrow", "nature", "nearly", "notice", "number", "object",
    "office", "orange", "period", "person", "places", "plenty", "reason", "record", "remain",
    "result", "return", "rather", "second", "seemed", "shadow", "should", "signal", "simple",
    "single", "slowly", "source", "spread", "square", "strong", "supply", "system", "taking",
    "though", "toward", "travel", "unless", "unlike", "useful", "volume", "weight", "window",
    "winter", "wonder", "yellow",
    "against", "already", "amongst", "another", "balance", "because", "between", "brought",
    "careful", "certain", "changed", "climate", "collect", "compare", "concern", "connect",
    "content", "correct", "crossed", "current", "deliver", "develop", "distant", "eastern",
    "element", "evening", "example", "explain", "explore", "feeling", "figures", "finally",
    "fitting", "forward", "further", "gathers", "general", "however", "imagine", "improve",
    "include", "instead", "kitchen", "leading", "measure", "meeting", "morning", "mystery",
    "natural", "neither", "nothing", "operate", "opinion", "outside", "pattern", "perhaps",
    "picture", "present", "problem", "process", "produce", "purpose", "quality", "quickly",
    "reading", "reasons", "receive", "release", "removed", "require", "respect", "reveals",
    "science", "section", "serious", "several", "similar", "society", "special", "station",
    "storage", "strange", "subject", "support", "surface", "thought", "through", "trouble",
    "usually", "village", "weather", "welcome", "western", "whether", "willing", "without",
    "working", "written",
    "absolute", "actually", "although", "anything", "argument", "attached", "boundary",
    "building", "carrying", "clearly", "complete", "consider", "constant", "continue",
    "creature", "decision", "describe", "detailed", "differed", "directly", "distance",
    "document", "eventual", "evidence", "exchange", "expected", "exposure", "familiar",
    "february", "flexible", "followed", "generate", "gradient", "happened", "hardware",
    "however", "improved", "increase", "interest", "involved", "language", "learning",
    "material", "mechanic", "midnight", "moderate", "mountain", "movement", "national",
    "occupied", "opposite", "ordinary", "original", "particle", "personal", "physical",
    "position", "possible", "practice", "prepared", "pressure", "probably", "produced",
    "properly", "provided", "question", "reaching", "received", "recorded", "relative",
    "remember", "removing", "repeated", "reported", "resemble", "resolved", "sequence",
    "shoulder", "situated", "solution", "somebody", "sometime", "southern", "specific",
    "standard", "strength", "stronger", "struggle", "suitable", "surprise", "surround",
    "thinking", "thousand", "together", "traffic", "training", "transfer", "traveled",
    "universe", "unlikely", "valuable", "variable", "watching", "whatever", "whenever",
    "wherever", "although",
)

# The sentence templates the reference answers are built from. Several of them carry the exact
# shapes the sentence rule has to survive, a decimal number and an abbreviation, so a reference
# answer that is CORRECT under the published rule is visibly graded WRONG under the naive one.
SENTENCE_STEMS = (
    "The {keyword} matters more than most people notice",
    "Dr. Halloway wrote about {keyword} for twenty years",
    "Roughly 3.5 percent of the work involves {keyword}",
    "Any account of this has to mention {keyword} early",
    "The {keyword} is where the whole thing turns",
    "Books on the subject, e.g. the older ones, treat {keyword} carefully",
    "Nobody agrees about {keyword}, and that is the interesting part",
    "Watch the {keyword} and the rest explains itself",
    "It takes about 2.5 hours before the {keyword} settles",
    "The St. Aubyn account of {keyword} is the readable one",
)

ITEM_STEMS = (
    "The {keyword} is easy to overlook",
    "Cold weather changes the {keyword}",
    "Older accounts of the {keyword} disagree",
    "Measuring the {keyword} takes patience",
    "The {keyword} was named later than the rest",
    "Most descriptions start at the {keyword}",
    "A second look at the {keyword} pays off",
    "The {keyword} behaves differently at night",
    "Nothing here works without the {keyword}",
    "The {keyword} is the part people photograph",
    "Every account mentions the {keyword} at least once",
    "The {keyword} rewards a slow reader",
    "Field notes about the {keyword} are worth reading",
    "The {keyword} is the reason the shape is what it is",
    "One good drawing of the {keyword} explains more than a page",
    "The {keyword} was misunderstood for a long time",
)
